version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed-socketio-passport-example/server:latest
    ports:
      - '8081:8081'
  mongodb:
    image: mongo:7.0.0
    ports:
      - '27017:27017'
